WISDEM/WOMBAT

wombat/core/environment.py, wombat/utilities/utilities.py
This PR removes the `StreamHandler` and adds a `MemoryHandler` with the same target file structure. By storing some of the logging messages in memory and writing them to file all at once, the runtimes see minor speedups. To ensure everything gets written correctly, the `WombatEnvironment.run()` method catches all errors, flushes the logs, then re-raises the error.
=> Update the logging for minor speedups

wombat/core/simulation_api.py, wombat/windfarm/system/cable.py, wombat/windfarm/system/subassembly.py
This PR fixes an issue with an interruption occurring before a maintenance or failure starts processing the timeout, so an UnboundLocalError is raised for the start time not yet being defined.
=> Bug fix: interruption timing

CHANGELOG.md, wombat/core/port.py, wombat/core/service_equipment.py
This PR addresses three issues:
- Another negative delay edge case in the crew transfer process caused by not exiting recursive loops properly
- Duplicated fields in `log_action` during complex repair logic
- Improper vessel management at ports where all tugboats are assumed to be TOW- and AHV- capable
=> Bug fix: Duplicate log args & Improper port vessel management

CHANGELOG.md, tests/test_service_equipment.py, wombat/core/service_equipment.py
This PR fixes erroneous logic causing weather delays to be processed twice due to improper control flow.
Closes #80
=> Bug Fix: Only Process Weather Delays Once

CHANGELOG.md, wombat/core/port.py, wombat/core/repair_management.py, wombat/core/service_equipment.py, wombat/core/simulation_api.py
This PR fixes an issue where it ports operating tow-to-port and in situ repairs seemingly stop working by implementing the following fixes:
- consolidated the dispatching logic to port-based and manager-based dispatching, and separately calling tow-to-port repairs
- Managed the port-based dispatching of vessels to align with tow-only or other capabilities to ensure that non-tow operations don't crowd out the requests for tow-to-port and tow-to-site operations
- Ports now only have one vessel management queue, regardless of vessel type to help with the above solution
=> Bug fix: Port Stops Processing Tow-To-Port

CHANGELOG.md, tests/test_service_equipment.py, wombat/core/data_classes.py, wombat/core/port.py, wombat/core/repair_management.py, wombat/core/service_equipment.py
This PR addresses three inter-related issues:
1. Operating levels > 100% due to the subassembly reset process' improper use of multiple if statements in place of a longer if/elif block
2. Repairs being completed more than once due to an improper recursive loop in the crew transfer mechanisms during shift delays
3. Repairs having equipment dispatched more than once due to inconsistent handling of pending, processing, and completed repair statuses
See the changelog for complete details.
=> Bug Fix: Repair duplication and multiple completions

.github/workflows/python-publish-test.yml
This PR silences a GH Action warning stemming from  a change in configuration key naming conventions.
=> Update Test PyPI action settings

wombat/core/simulation_api.py
This PR fixes an issue where `Simulation.from_config()` generates the `cls` object while referencing `cls` properties improperly, instead of `config`.
=> Bug Fix: Improper use of `cls`

CHANGELOG.md, pyproject.toml, tests/test_repair_manager.py, tests/test_service_equipment.py, wombat/core/environment.py, wombat/core/port.py, wombat/core/repair_management.py, wombat/core/service_equipment.py, wombat/windfarm/system/cable.py, wombat/windfarm/system/system.py
This PR addresses a series of logic holes:
- Servicing equipment can no longer travel when their expected finish time is in the following shift, but after the original shift's end time
- Repairs with delays that are incomplete at the end of the original forecast window now consistently register as having a shift delay instead of being complete
- Systems wait until a servicing equipment has arrived and is going to transfer the crew to interrupt it and shut it down, rather than at the onset of traveling to the system.
See the changelog for complete details. All changes result in a small net positive increase in availability due to better resolved timing of shut downs and repairs.
=> Bug Fix: Ensure system downtime starts appropriately

CHANGELOG.md, wombat/core/post_processor.py, wombat/core/repair_management.py, wombat/windfarm/windfarm.py
This PR addresses vagueness in the logging of the completion of repairs and maintenance tasks. See the changelog for details.
=> Bug fix: Task completion rate clarity

CHANGELOG.md, wombat/core/environment.py
This PR resolves an edge case where a crew transfer gets initiated for midnight after the end of the last day of the simulation by checking the timestamp in the environment's logging method and ignoring any log occurring after that.
=> Bug Fix: Keep logged events within the timing bounds

docs/_config.yml
This PR fixes a link where the documention's GitHub source link incorrectly pointed to the NREL/WAVES repository.
=> Patch: Fix bad repository link

.pre-commit-config.yaml, CHANGELOG.md, pyproject.toml, wombat/core/data_classes.py, wombat/windfarm/windfarm.py
This PR replaces the `black` formatter with the `ruff` formatter, and adopts `pyupgrade`.
=> Maintenance: Adopt Ruff Formatter and Pyupgrade

CHANGELOG.md, wombat/core/post_processor.py
This PR fixes the logic that produces 100% or just under TBA for nearly any simulation.
=> Bug Fix: Restore time-based-availability

wombat/core/simulation_api.py
This PR addresses #141 by bringing the configuration's random seeding variables up to the `Simulation` level, making it consistent with the `Simulation.from_config()` logic.
=> Bug Fix: Enable random seeding from the configuration universally.

CHANGELOG.md, wombat/core/service_equipment.py, wombat/utilities/utilities.py
This PR fixes a previously unknown issue that modifies the `Subassembly.id` to rename subassemblies such as "mooring_1" to "mooring". This creates a naming overlap that doesn't causes errors unless there are replacement events, which then cause each identically named subassembly to have invalidated processes, rather than just the failing one. Subassembly IDs are now stripped of leading punctuation and digits and have all punctuation replaced with underscores.
=> Fix subassembly ID creation to not strip non-leading numerals

wombat/core/data_classes.py
This PR fixes an incorrect reference to "AHV" in `StrategyMap.move_equipment_to_end` where the "VSG" category moves a vessel in the "AHV" category, not "VSG".
=> Fix bad capability code in strategy map

CHANGELOG.md, README.md, docs/install.md
This PR addresses out of date Python versioning references and installation instructions in the README and documentation site.
=> Documentation: Update the installation instructions

CHANGELOG.md, wombat/core/service_equipment.py, wombat/utilities/__init__.py, wombat/utilities/utilities.py, wombat/windfarm/windfarm.py
This PR removes support for the older Python versions' caching methods in favor of `functools.cache`. This also removes the need to import the standardized `cache` from utilities, and directly imports `functools.cache` across WOMBAT.
=> Update `functool.cache` usage

.pre-commit-config.yaml, CHANGELOG.md, wombat/core/environment.py, wombat/core/post_processor.py
This PR fixes a bug where the substation availability was not being consistently counted against the upstream turbine's availability for both the turbine- and wind farm-level aggregation. This will have a modest impact on end availability results.
Kudos to @dmulash for identifying the discrepancy!
=> Bug Fix: Address Inconsistenty in Turbine vs. Wind Farm Availability

CHANGELOG.md, wombat/core/library.py
This PR fixes a bug causing PyYAML to raise a `ResourceWarning` because of unclosed files by using a context manager to open the file and return its contents.
=> PATCH: Fix YAML loading bug causing `ResourceWarning`

.github/workflows/python-publish-test.yml, .github/workflows/python-publish.yml, CHANGELOG.md
This PR removes the unnecessary secrets passing for a trusted publisher workflow. Due to changes in the GH Action, the redundant permissions now fail, and so it must be removed to publish successfully.
=> PATCH: Fix PyPI publishing workflow

.github/workflows/python-publish-test.yml, .github/workflows/python-publish.yml
This PR adds the missing and mandatory permissions configuration for PyPI's trusted publishing.
=> PATCH: PyPI publishing permissions

CHANGELOG.md, tests/test_service_equipment.py, wombat/__init__.py, wombat/windfarm/system/subassembly.py
This PR partially addresses an ongoing issue found in #154 by reinstating the conversion from `Maintenance.frequency`'s units of days to the simulation's base of hours.
=> Fix: Maintenance Frequency Conversion

CHANGELOG.md, tests/test_service_equipment.py, wombat/__init__.py, wombat/windfarm/system/subassembly.py
This reverts commit 58f500d648660fd7789521ea103beee618dd1124, which erroneously "fixed" a timing issue. The reversion undoes that work which had actually just been moved to a more logical spot in the code.
=> Revert: "Fix: Maintenance Frequency Conversion (#169)"

wombat/utilities/plot.py
When using DatetimeIndex.to_period('m') pandas throws a FutureWarning and advice to use 'M' instead
pandas.__version == '2.2.2'
=> Fix pandas Depreciation warning in plot

CHANGELOG.md, docs/API/types.md, docs/examples/how_to.md, docs/examples/index.md, pyproject.toml, tests/test_cable.py, tests/test_data_classes.py, wombat/core/data_classes.py, wombat/windfarm/system/cable.py, wombat/windfarm/system/subassembly.py
This PR enables two modes of frequency bases: date-based, fixed interval frequency and relative frequency to ensure that strict maintenance schedules can be modeled. In addition, this PR also adds in support for starting dates, which can be used in either mode. For a complete sketch of the functionality, please see either the comments in #66 or the [CHANGELOG.md](https://github.com/WISDEM/WOMBAT/blob/feature/date-based-maintenance/CHANGELOG.md).
The documentation and testing have also been updated to ensure that the functionality works as expected.
Closes #66
=> Feature: Expand Maintenance Frequency Defintions

.github/workflows/gh_pages.yml
This PR updates the GH Pages artifact uploading version.
=> Fix: Bump upload artifact for gh pages

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, tests/test_cable.py, tests/test_data_classes.py, tests/test_subassembly.py, wombat/__init__.py, wombat/core/data_classes.py, wombat/core/environment.py, wombat/windfarm/system/cable.py, wombat/windfarm/system/subassembly.py
This PR fixes an uncaught bug in the development of the date-based maintenance feature released in 0.10. When a subassembly is replaced, the conversion of the user input to a timeout schedule was triggered again. This reinitialization caused runs to fail because of improper type interactions. This update ensures the setup logic is only run at subassembly initialization.
N/A
- Updates buffer for maintenance events
- `test/test_subassembly.py`
- `test/test_data_classes.py`
- test/test_cable.py`
- Ensures maintenance is initialized once
- `wombat/windfarm/system/cable.py`
- `wombat/windfarm/system/subassembly.py`
- `wombat/core/environment.py`: fixes a future warning for pandas offsets
- `wombat/core/data_classes.py`: change buffer from 1 hour to 1 day
Python version: 3.x
WOMBAT version …
=> Fix: Improper reinitialization of maintenance event timing

CHANGELOG.md, wombat/__init__.py, wombat/core/service_equipment.py
This PR fixes two small issues in the servicing equipment logic.
1. Unscheduled servicing equipment now check if they have not been mobilized and there are no requests they can address. When this is the case, they now cancel their dispatching without accruing any costs.
2. The end of simulation check in travel time is updated for compatibility with Python's datetime (microsecond resolution) and PolaRS' datetime (nanosecond resolution).
N/A
- `wombat/core/service_equipment.py`
- `ServiceEquipment.run_unscheduled_in_situ()`: A bug where excess unproductive accumulates for tow-to-port scenarios was caused by the port taking over repair requests from a vessel between its initial dispatching and its mobilization. When this occurred, the vessel would operate for the charter and mobilization …
=> Patch: Dispatch timing conflict & end of simulation check

CHANGELOG.md, wombat/core/service_equipment.py, wombat/windfarm/system/cable.py, wombat/windfarm/system/subassembly.py
This PR adds additional diagnostic information to any error messages that occur during the data validation step of the cable, system, and service equipment initialization.
N/A
- `try`/`except`/`raise from` clause wrapped around the data class validation
- `wombat/windfarm/system/subassembly.py::Subassembly.__init__()`
- `wombat/windfarm/system/cable.py::Cable.__init__()`
- `wombat/core/service_equipment.py::ServiceEquipment.__init__()`
Python version: 3.x
WOMBAT version (`wombat.__version__`): 0.x
N/A
=> Enhancement: Initialization error message improvements

CHANGELOG.md, tests/conftest.py, tests/library/project/config/base.yml, tests/test_environment.py, tests/test_simulation_api.py, wombat/core/data_classes.py, wombat/core/environment.py, wombat/core/simulation_api.py, wombat/utilities/time.py, wombat/windfarm/system/cable.py, wombat/windfarm/system/subassembly.py
This PR expands the new maintenance starting date feature to include a universalized starting date that can be set through the main configuration file. This primary functionality of this feature is to enable scenarios where a weather profiles starts with a new year, but maintenance timing would start in the summer for the Northern Hemisphere. By staggering the starting time universally, this significantly reduces the cost of maintenance activity that may suffer from extensive delays due to harsh weather conditions.
N/A
- Primary configurations have been updated to include the new input and handle, string, datetime, and None inputs.
- `wombat/core/environment.py::WombatEnvironment`
- `wombat/core/simulation_api.py::Configuration`
- `wombat/core/simulation_api.py::Simulation`
- Anywhere …
=> Enhancement: Universal maintenance starting date

tests/test_data_classes.py, wombat/core/data_classes.py, wombat/core/post_processor.py
This PR contributes the following fixes for the develop branch:
- Removes extra print statements introduced in the updated `component_costs`.
- Fixes the double counting of materials costs that are introduced when port-based logging is captured in `component_costs`
- Fixes an edge case where maintenance events occurring on the last day of the simulation hit the end of their pre-produced limits, so a second buffer date is included.
N/A
- `wombat/core/post_processor.py`
- `Metrics.component_costs()`: Removed two print statements, and the extraneous port data capture that double-counts costs
- `wombat/core/data_classes.py`
- `Maintenance._update_event_timing()`: Produces a second buffer date after the end of the simulation.
- `tests/test_data_classes.py`
- `test_Maintenance_frequency(): Adds …
=> Patch: Minor metrics and simulation timing updates

CHANGELOG.md, tests/unit/test_simulation_api.py, wombat/core/environment.py, wombat/core/post_processor.py, wombat/core/simulation_api.py
This PR enables the auto cleanup of log files through the new parameter `delete_log_files` in `Simulation.run()` to reduce the number of steps used for simulation running, results calculation, and cleanup. Crucially, this parameter is incompatible with default `save_metrics_inputs=True`, which must be set to False in order to automatically cleanup the log files. This is done to both preserve the default behavior and to ensure a user can't accidentally delete the log files prematurely.
Additionally, this PR converts all logged data to use the Parquet data format for faster I/O and efficient data storage.
N/A
- `wombat/core/environment.py`
- `WombatEnvironment.convert_logs_to_pqt()`: New method to convert the events and operations logs from .csv files to .pqt files immediately after …
=> Feature: Simulation auto cleanup and CSV -> Parquet

CHANGELOG.md, docs/API/simulation_api.md, docs/examples/metrics_demonstration.md, tests/conftest.py, tests/regression/test_results.py, wombat/core/post_processor.py
This PR fixes a bug in the `Metrics.process_times()` method that inappropriately counted cancled requests towards the total number of requests, which inflated both the timing and event summaries. To clarify which events are included, a new flag `include_incompletes` is created to ensure unfinsihed events can be in/excluded when necessary for investigating simulation results.
In addition, a new method `Metrics.request_summary()` has been created to count the total number of requests by subassembly and task, the number of canceld events, and the number of completed events, which can be used as an aid to calculating the per even statistics.
New tests have also been included to ensure the number of events is accurately represented in both metrics.
N/A
- `wombat/core/metrics/post_processor.py` …
=> Patch: Improve event counting

CHANGELOG.md, docs/examples/index.md, wombat/core/environment.py, wombat/core/library.py, wombat/core/port.py, wombat/core/repair_management.py, wombat/core/service_equipment.py, wombat/core/simulation_api.py, wombat/utilities/plot.py, wombat/utilities/time.py, wombat/windfarm/windfarm.py
This focuses on ensuring tugboats do not operate w.r.t. shift timing while disconnecting and reconnecting mooring lines for towing operations. To supplement this, the calculation of weather windows can now be calculated with or without the consideration of shift timing.
Further, all boolean inputs and arguments occurring after the first boolean are now forced to be called using the parameter's name as a strict keyword argument. Many methods and functions already enforced this, but many did not, so it is now an expected standard. The only exception (for now) is to allow any metrics calculations to continue passing booleans as a standard argument.
- [-] Examples have been updated
=> Feature: Enable shift ignorable tasks

CHANGELOG.md, tests/unit/test_data_classes.py, wombat/__init__.py, wombat/core/data_classes.py, wombat/core/port.py, wombat/core/post_processor.py, wombat/core/repair_management.py, wombat/core/service_equipment.py, wombat/windfarm/system/cable.py, wombat/windfarm/system/subassembly.py, wombat/windfarm/system/system.py
This patch PR fixes 3 interrelated issues:
1. Ensure date-based maintenance uses the correct inuring priority order of using the individual task's specification, then the environment-wide specification, when provided
2. Ensures that when a subassembly is replaced, it is always has its processes reset. This was particularly an issue with tow-to-port repairs that had date-based maintenance tasks occur while at port, causing compounding numbers of additional processes to be created silently. The runaway processes would duplicate with each tow-to-port repair cycle inflating the number of simulated maintenance tasks, failures, and all dependent results.
3. Removes duplicated request ID counts in the metrics caused cable-based logging duplication for when upstream processes are shut down, and …
=> Patch: Fixed date maintenance timing and runaway processes

.github/workflows/ci-tests.yml, CHANGELOG.md, pyproject.toml
This PR installs an extra dependency required to run `polars` on apple silicon chips. It also include testing on MacOS runners.
- [-] Examples have been updated
- `pyproject.toml`: add `polars-lts-cpu`: as a required dependency for MacOS
- `.github/workflows/ci-tests.yml`: run tests on MacOS
WOMBAT tests were failing in H2I and the problem was tracked to the `polars` as a dependency of WOMBAT
Python version: 3.11
WOMBAT version (`wombat.__version__`): 0.11.2
=> Fix: Polars compatibility with Apple Silicon
